version: '3.7'
services:
  app:
    build: .
    container_name: crowdtweet
    image: crowdtweet:latest
    volumes:
      - ./:/app
    environment:
      TWITTER_API_KEY: ""
      TWITTER_API_SECRET_KEY: ""
      BEARER_TOKEN: ""
      SECRET_KEY: ""
      DB_HOST: ""
      DB_USER: ""
      DB_PASS: ""
      DB_NAME: ""
    ports:
      - "4000:4000"

  rabbitmq:
    image: rabbitmq:3.11.25
    container_name: rabbitmq
    expose:
      - 5672
    ports:
      - 5672:5672

  celery:
    image: celery
    container_name: celery
    expose:
      - 27017
    ports:
      - 27017:27017

