version: 3.0.0
services:
  app:
    build: .
    container_name: crowdtweet
    image: crowdtweet:latest
    volumes:
      - ./:/app
    environment:
      TWITTER_API_KEY: ""
      TWITTER_API_SECRET_KEY: ""
      BEARER_TOKEN: ""
      SECRET_KEY: ""
      DB_HOST: ""
      DB_USER: ""
      DB_PASS: ""
      DB_NAME: ""
    ports:
      - 4000:4000

